In [1]:
#Dependencies
import pandas as pd
import numpy as np
import requests
import json
import csv
import pymongo
from flask import Flask, render_template

In [2]:
#Import CSV
# Import cities file as DataFrame
inflation_index = pd.read_csv("Resources/Inflation-data.csv")
inflation_index.head()

,Country Code,IMF Country Code,Country,Indicator Type,Series Name,1970,1971,1972,1973,1974,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,AFG,512.0,Afghanistan,Inflation,Estimated Core Consumer Price Inflation,NaN,NaN,NaN,NaN,NaN,...,5.81,6.30,7.44,1.67,3.86,2.46,2.63,2.95,NaN,NaN
1,ALB,914.0,Albania,Inflation,Estimated Core Consumer Price Inflation,NaN,NaN,NaN,NaN,NaN,...,2.16,0.52,1.23,1.47,-0.80,0.61,1.17,0.34,-0.06,0.89
2,DZA,612.0,Algeria,Inflation,Estimated Core Consumer Price Inflation,NaN,NaN,NaN,NaN,NaN,...,6.73,3.65,2.34,5.54,9.13,6.75,5.74,4.31,4.60,5.72
3,AGO,614.0,Angola,Inflation,Estimated Core Consumer Price Inflation,NaN,NaN,NaN,NaN,NaN,...,9.00,7.23,8.70,10.27,28.97,38.05,24.32,16.00,NaN,NaN
4,ARG,213.0,Argentina,Inflation,Estimated Core Consumer Price Inflation,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,31.89,52.52,43.76,51.42

In [3]:
#check columns
inflation_index.columns

Index(['Country Code', 'IMF Country Code', 'Country', 'Indicator Type',
       'Series Name', '1970', '1971', '1972', '1973', '1974', '1975', '1976',
       '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985',
       '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994',
       '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003',
       '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012',
       '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021'],
      dtype='object')

In [4]:
# drop columns 1970-2010
inflation_index = inflation_index.drop(["1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", 
                                        "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", 
                                        "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", 
                                        "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009",
                                        "2010"], axis=1)
inflation_index.head()

,Country Code,IMF Country Code,Country,Indicator Type,Series Name,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,AFG,512.0,Afghanistan,Inflation,Estimated Core Consumer Price Inflation,13.12,5.81,6.30,7.44,1.67,3.86,2.46,2.63,2.95,NaN,NaN
1,ALB,914.0,Albania,Inflation,Estimated Core Consumer Price Inflation,2.83,2.16,0.52,1.23,1.47,-0.80,0.61,1.17,0.34,-0.06,0.89
2,DZA,612.0,Algeria,Inflation,Estimated Core Consumer Price Inflation,5.41,6.73,3.65,2.34,5.54,9.13,6.75,5.74,4.31,4.60,5.72
3,AGO,614.0,Angola,Inflation,Estimated Core Consumer Price Inflation,13.72,9.00,7.23,8.70,10.27,28.97,38.05,24.32,16.00,NaN,NaN
4,ARG,213.0,Argentina,Inflation,Estimated Core Consumer Price Inflation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.89,52.52,43.76,51.42

In [12]:
inflation= inflation_index.groupby("Country")
inflation.head()

,Country Code,IMF Country Code,Country,Indicator Type,Series Name,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,AFG,512.0,Afghanistan,Inflation,Estimated Core Consumer Price Inflation,13.12,5.81,6.30,7.44,1.67,3.86,2.46,2.63,2.95,NaN,NaN
1,ALB,914.0,Albania,Inflation,Estimated Core Consumer Price Inflation,2.83,2.16,0.52,1.23,1.47,-0.80,0.61,1.17,0.34,-0.06,0.89
2,DZA,612.0,Algeria,Inflation,Estimated Core Consumer Price Inflation,5.41,6.73,3.65,2.34,5.54,9.13,6.75,5.74,4.31,4.60,5.72
3,AGO,614.0,Angola,Inflation,Estimated Core Consumer Price Inflation,13.72,9.00,7.23,8.70,10.27,28.97,38.05,24.32,16.00,NaN,NaN
4,ARG,213.0,Argentina,Inflation,Estimated Core Consumer Price Inflation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.89,52.52,43.76,51.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,URY,298.0,Uruguay,Inflation,Estimated Core Consumer Price Inflation,6.97,7.71,7.18,8.17,8.44,9.74,7.15,7.64,7.95,10.92,8.11
153,VEN,299.0,"Venezuela, RB",Inflation,Estimated Core Consumer Price Inflation,12.32,9.53,10.14,4.26,0.73,2.95,6.72,3.84,1.76,NaN,NaN
154,VNM,582.0,Vietnam,Inflation,Estimated Core Consumer Price Inflation,3.21,3.03,1.97,2.41,2.50,1.19,0.43,-0.03,0.66,-0.60,2.69
155,ZMB,754.0,Zambia,Inflation,Estimated Core Consumer Price Inflation,NaN,NaN,7.19,8.04,9.48,16.71,6.41,6.79,8.31,13.96,NaN
156,ZWE,698.0,Zimbabwe,Inflation,Estimated Core Consumer Price Inflation,3.19,3.29,1.61,1.26,-1.96,-0.68,0.07,8.48,NaN,NaN,NaN

In [21]:
#Pull Country United States
inflation_clean= inflation.get_group("United States")
inflation_clean

,Country Code,IMF Country Code,Country,Indicator Type,Series Name,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
151,USA,111.0,United States,Inflation,Estimated Core Consumer Price Inflation,3.88,2.21,0.99,0.63,-1.4,0.75,1.73,2.35,1.23,NaN,NaN

In [22]:
#convert to Json
inflation_clean.to_json()

'{"Country Code":{"151":"USA"},"IMF Country Code":{"151":111.0},"Country":{"151":"United States"},"Indicator Type":{"151":"Inflation"},"Series Name":{"151":"Estimated Core Consumer Price Inflation"},"2011":{"151":3.88},"2012":{"151":2.21},"2013":{"151":0.99},"2014":{"151":0.63},"2015":{"151":-1.4},"2016":{"151":0.75},"2017":{"151":1.73},"2018":{"151":2.35},"2019":{"151":1.23},"2020":{"151":null},"2021":{"151":null}}'